spring.application.name=catraca

cloudinary.cloud_name=dbwckc31p
cloudinary.api_key=123817962447412
cloudinary.api_secret=1B6uHSLxTWPExbM9weU68t-g2ss

spring.cache.type=caffeine
spring.cache.cache-names=alunos
spring.cache.caffeine.spec=expireAfterWrite=10m,maximumSize=500

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cifasuporte@gmail.com
spring.mail.password=vciw fmug yrld vttx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

